In [46]:
import pandas as pd
import numpy as np

In [47]:
s=pd.Series([1,2,3,4, np.nan, 6,7])
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
dtype: float64

In [48]:
dates=pd.date_range("20170211", periods=6)
dates

DatetimeIndex(['2017-02-11', '2017-02-12', '2017-02-13', '2017-02-14',
               '2017-02-15', '2017-02-16'],
              dtype='datetime64[ns]', freq='D')

In [49]:
np.random.randn(6,4)


array([[-0.6584927 , -0.1746331 , -0.79413667,  1.3542444 ],
       [ 0.44391999, -0.25409557,  0.28186866,  0.82510969],
       [-1.11023114, -0.59583226,  0.5146357 ,  0.63134709],
       [-1.90829126,  1.6786294 , -2.91634067,  0.19143378],
       [-0.81640671, -0.01869107, -1.16705691, -2.80306402],
       [ 0.49045888,  1.74813732, -0.67041926, -0.49607744]])

In [50]:
df=pd.DataFrame(np.random.randn(6,4), index= dates, columns=list('ABCD'))
df

A         B         C         D
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

Creating a DataFrame by passing a dictionary of objects where the keys are the column labels and the values are the column values.

In [51]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series((1,2,3,4), index=list(range(4)), dtype="int32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

A          B  C  D      E    F
0  1.0 2013-01-02  1  3   test  foo
1  1.0 2013-01-02  2  3  train  foo
2  1.0 2013-01-02  3  3   test  foo
3  1.0 2013-01-02  4  3  train  foo

In [52]:
df2.dtypes

A          float64
B    datetime64[s]
C            int32
D            int32
E         category
F           object
dtype: object

Viewing Data

In [53]:
df.head(2)

A         B         C        D
2017-02-11 -0.806102  0.966440 -2.008228  0.31331
2017-02-12 -0.144664 -1.652825  0.517022  1.04422

In [54]:
df.tail(3)

A         B         C         D
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

In [55]:
df.abs()

A         B         C         D
2017-02-11  0.806102  0.966440  2.008228  0.313310
2017-02-12  0.144664  1.652825  0.517022  1.044220
2017-02-13  0.124551  0.022523  0.192469  1.054225
2017-02-14  0.182518  1.045229  0.661756  1.558312
2017-02-15  0.875753  0.515257  1.294358  1.151982
2017-02-16  1.099485  0.437896  0.534614  0.482830

In [56]:
df.index

DatetimeIndex(['2017-02-11', '2017-02-12', '2017-02-13', '2017-02-14',
               '2017-02-15', '2017-02-16'],
              dtype='datetime64[ns]', freq='D')

In [57]:
df.set_index('B')
df

A         B         C         D
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

In [58]:
df.reset_index()

index         A         B         C         D
0 2017-02-11 -0.806102  0.966440 -2.008228  0.313310
1 2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2 2017-02-13  0.124551 -0.022523  0.192469 -1.054225
3 2017-02-14  0.182518  1.045229 -0.661756 -1.558312
4 2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
5 2017-02-16 -1.099485  0.437896  0.534614 -0.482830

In [59]:
df

A         B         C         D
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

In [60]:
df.to_numpy()

array([[-0.80610228,  0.96644036, -2.00822755,  0.31331019],
       [-0.14466352, -1.65282454,  0.51702198,  1.04422024],
       [ 0.12455132, -0.02252261,  0.19246868, -1.05422527],
       [ 0.18251811,  1.04522922, -0.66175611, -1.55831174],
       [-0.87575348, -0.51525736,  1.2943578 , -1.15198234],
       [-1.09948481,  0.43789637,  0.5346143 , -0.4828299 ]])

NumPy arrays have one dtype for the entire array while pandas DataFrames have one dtype per column

In [61]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 2, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 3, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 4, 3, 'train', 'foo']],
      dtype=object)

In [62]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.436489  0.043160 -0.021920 -0.481636
std    0.557177  1.020286  1.160478  0.989609
min   -1.099485 -1.652825 -2.008228 -1.558312
25%   -0.858341 -0.392074 -0.448200 -1.127543
50%   -0.475383  0.207687  0.354745 -0.768528
75%    0.057248  0.834304  0.530216  0.114275
max    0.182518  1.045229  1.294358  1.044220

Transpose

In [63]:
df.T    

2017-02-11  2017-02-12  2017-02-13  2017-02-14  2017-02-15  2017-02-16
A   -0.806102   -0.144664    0.124551    0.182518   -0.875753   -1.099485
B    0.966440   -1.652825   -0.022523    1.045229   -0.515257    0.437896
C   -2.008228    0.517022    0.192469   -0.661756    1.294358    0.534614
D    0.313310    1.044220   -1.054225   -1.558312   -1.151982   -0.482830

In [64]:
df2.T

0                    1                    2  \
A                  1.0                  1.0                  1.0   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                    1                    2                    3   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                  1.0  
B  2013-01-02 00:00:00  
C                    4  
D                    3  
E                train  
F                  foo

Sort by an index

In [65]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2017-02-11  0.313310 -2.008228  0.966440 -0.806102
2017-02-12  1.044220  0.517022 -1.652825 -0.144664
2017-02-13 -1.054225  0.192469 -0.022523  0.124551
2017-02-14 -1.558312 -0.661756  1.045229  0.182518
2017-02-15 -1.151982  1.294358 -0.515257 -0.875753
2017-02-16 -0.482830  0.534614  0.437896 -1.099485

In [66]:
df.sort_values(by="B")

A         B         C         D
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-16 -1.099485  0.437896  0.534614 -0.482830
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-14  0.182518  1.045229 -0.661756 -1.558312

## GetItem([])

In [67]:
df['A']

2017-02-11   -0.806102
2017-02-12   -0.144664
2017-02-13    0.124551
2017-02-14    0.182518
2017-02-15   -0.875753
2017-02-16   -1.099485
Freq: D, Name: A, dtype: float64

In [68]:
df2

A          B  C  D      E    F
0  1.0 2013-01-02  1  3   test  foo
1  1.0 2013-01-02  2  3  train  foo
2  1.0 2013-01-02  3  3   test  foo
3  1.0 2013-01-02  4  3  train  foo

In [69]:
df2[0:3]

A          B  C  D      E    F
0  1.0 2013-01-02  1  3   test  foo
1  1.0 2013-01-02  2  3  train  foo
2  1.0 2013-01-02  3  3   test  foo

In [70]:
df

A         B         C         D
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

# Selection by label

In [71]:
df.loc[dates[0]]

A   -0.806102
B    0.966440
C   -2.008228
D    0.313310
Name: 2017-02-11 00:00:00, dtype: float64

Selecting all rows (:) with a select column labels:

In [72]:
df.loc[:,['A','B']]

A         B
2017-02-11 -0.806102  0.966440
2017-02-12 -0.144664 -1.652825
2017-02-13  0.124551 -0.022523
2017-02-14  0.182518  1.045229
2017-02-15 -0.875753 -0.515257
2017-02-16 -1.099485  0.437896

In [73]:
df.loc['20170212':'20170214',['A','B']]

A         B
2017-02-12 -0.144664 -1.652825
2017-02-13  0.124551 -0.022523
2017-02-14  0.182518  1.045229

In [74]:
df.loc[dates[0], ["A"]]

A   -0.806102
Name: 2017-02-11 00:00:00, dtype: float64

In [75]:
df.at[dates[0], 'A']

-0.8061022785496211

# Selection by position

In [77]:
df

A         B         C         D
2017-02-11 -0.806102  0.966440 -2.008228  0.313310
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312
2017-02-15 -0.875753 -0.515257  1.294358 -1.151982
2017-02-16 -1.099485  0.437896  0.534614 -0.482830

In [76]:
df.iloc[3]

A    0.182518
B    1.045229
C   -0.661756
D   -1.558312
Name: 2017-02-14 00:00:00, dtype: float64

In [78]:
df.iloc[3:5, 0:2]

A         B
2017-02-14  0.182518  1.045229
2017-02-15 -0.875753 -0.515257

In [79]:
df.iloc[[1,2,4],[2,3]]

C         D
2017-02-12  0.517022  1.044220
2017-02-13  0.192469 -1.054225
2017-02-15  1.294358 -1.151982

In [81]:
df.iloc[:, 2:4]

C         D
2017-02-11 -2.008228  0.313310
2017-02-12  0.517022  1.044220
2017-02-13  0.192469 -1.054225
2017-02-14 -0.661756 -1.558312
2017-02-15  1.294358 -1.151982
2017-02-16  0.534614 -0.482830

In [82]:
df.iloc[1:4,:]

A         B         C         D
2017-02-12 -0.144664 -1.652825  0.517022  1.044220
2017-02-13  0.124551 -0.022523  0.192469 -1.054225
2017-02-14  0.182518  1.045229 -0.661756 -1.558312

In [84]:
df.iloc[1,1]

-1.6528245413928278

In [85]:
df.iat[1,1]

-1.6528245413928278